<footer>
      <div class="row">
        <!--Logo and Description-->
        <div class="col">
          <img src="images/Logo.png" alt ="logo" class = "logo">
          <p>We're passionate about connecting top talent with their dream jobs within the job-hunting industry for IT Employees. Our personalized approach, tailored to your unique skills, combined with our expertise and deep network will accelerate your career search. Ready to take the next step? Explore our current openings or get in touch for expert guidance.</p>
        </div>

        <!--Contact Info-->
        <div class="col">
          <h3>Contact<span class="underline"><span></span></span></h3>
          <h3 id ="email-id">Email us via:</h3>
          <h4>1. <a href="mailto:103804535@student.swin.edu.au">Bao</a></h4>
          <h4>2. <a href="mailto:104171146@student.swin.edu.au">Thong</a></h4>
          <h4>3. <a href="mailto:10477508@student.swin.edu.au">Tam</a></h4>
        </div>

        <!--Navigation-->
        <div class="col">
          <h3>Links <span class="underline"><span></span></span></h3>
            <ul>
              <li><a href="index.html">Home</a></li>
              <li><a href="about.html">About Us</a></li>
              <li><a href="enhancements.html">Enhancements</a></li>
              <li><a href="jobs.html">Job Descriptions</a></li>
              <li><a href="https://youtu.be/9ScsvjHyDCk">Group Video</a></li>
            </ul>
        </div>

        <!--Newsletter-->
        <div class="col">
          <h3>Newsletter<span class="underline"><span></span></span></h3>
          <form id="footer-form">
            <span class="fa-solid fa-envelope"></span>
            <input type="email" placeholder="Enter email please!">
            <button type="submit"><span class="fa-solid fa-newspaper">Apply</span></button>
          </form>
            <!--Social Icons-->
          <div class="social-icons">
            <span class="fa-brands fa-square-facebook"></span>
            <span class="fa-brands fa-square-twitter"></span>
            <span class="fa-brands fa-linkedin"></span>
          </div>
        </div>
      </div>
      <hr>
      <p class="copyright">&copy;<a href = "https://www.swinburne.edu.au">Swinburne University of Technology</a></p>
    </footer>
